### ISSUE TITLE
where is the system.cfg file?

### ISSUE THREAD

**Issue by ahustr** [usc-sail/fed-multimodal#3]
Thank you for your fantastic work, but when i run the 'python3 features/data_partitioning/uci-har/data_partition.py --alpha 0.1 --num_clients 5', i can't find the file system.cfg, could you tell me where the file is?

**Comment by tiantiaf0627** [comment]
Thanks for pointing it out. It was missing in the commit when we were cleaning the code, and moving files around. I have now added it to the repo

**Comment by ahustr** [comment]
Thank you very much!
